server:
  port: 9110
# Database configuration 
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/properties_prod?createDatabaseIfNotExist=true"
    username: root
    password: Abhishek@123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true  

#Eureka Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
contact:
  info:
    username: "Abhishek Kumar"
    phone: "7765076652"
    email: "abhishek.kumar@gmail.com"
  user:
    message: "Welcome to the booking service in production Environment"
